# Book settings
title: "FactorLib 因子分析平台"
author: "黃天瑜"
logo: _static/logo.png
language: "zh"

html:
  favicon: _static/logo.png  
  navbar_logo: true          
  toc:
    use_permalinks: false
  use_multitoc_numbering: false